{
  'targets': [
    {
      'target_name': 'base',
      'type': 'static_library',
      'direct_dependent_settings': {
        'include_dirs': [
          'src',
        ],
      },
      'include_dirs': [
        'src',
      ],
      'sources': [
        'src/base/atomicops.h',
        'src/base/atomicops_internals_arm_gcc.h',
        'src/base/atomicops_internals_atomicword_compat.h',
        'src/base/atomicops_internals_gcc.h',
        'src/base/atomicops_internals_mac.h',
        'src/base/atomicops_internals_mips_gcc.h',
        'src/base/atomicops_internals_tsan.h',
        'src/base/atomicops_internals_x86_gcc.cc',
        'src/base/atomicops_internals_x86_gcc.h',
        'src/base/atomicops_internals_x86_msvc.h',
        'src/base/atomic_ref_count.h',
        'src/base/base_export.h',
        'src/base/basictypes.h',
        'src/base/bind.h',
        'src/base/bind_helpers.cc',
        'src/base/bind_helpers.h',
        'src/base/bind_internal.h',
        'src/base/bind_internal_win.h',
        'src/base/callback.h',
        'src/base/callback_forward.h',
        'src/base/callback_helpers.cc',
        'src/base/callback_helpers.h',
        'src/base/callback_internal.cc',
        'src/base/callback_internal.h',
        'src/base/callback_registry.h',
        'src/base/cancelable_callback.h',
        'src/base/compiler_specific.h',
        'src/base/logging.h',
        'src/base/memory/raw_scoped_refptr_mismatch_checker.h',
        'src/base/memory/ref_counted.cc',
        'src/base/memory/ref_counted.h',
        'src/base/memory/scoped_handle.h',
        'src/base/memory/scoped_policy.h',
        'src/base/memory/scoped_ptr.h',
        'src/base/memory/scoped_vector.h',
        'src/base/memory/weak_ptr.cc',
        'src/base/memory/weak_ptr.h',
        'src/base/move.h',
        'src/base/port.h',
        'src/base/stl_util.h',
        'src/base/template_util.h',
        'src/base/third_party/dynamic_annotations/dynamic_annotations.c',
        'src/base/third_party/dynamic_annotations/dynamic_annotations.gyp',
        'src/base/third_party/dynamic_annotations/dynamic_annotations.h',
        'src/base/third_party/dynamic_annotations/LICENSE',
        'src/base/third_party/dynamic_annotations/README.chromium',
        'src/base/third_party/valgrind/LICENSE',
        'src/base/third_party/valgrind/memcheck.h',
        'src/base/third_party/valgrind/README.chromium',
        'src/base/third_party/valgrind/valgrind.h',
        'src/base/threading/thread_collision_warner.cc',
        'src/base/threading/thread_collision_warner.h',
        'src/base/tuple.h',
        'src/build/build_config.h',
      ],
    },
  ],
}
